services:
  oxid_esales.command.module_activate_command:
    class: OxidEsales\EshopCommunity\Internal\Module\Command\ModuleActivateCommand
    public: true
    tags:
    - { name: 'console.command', command: 'oe:module:activate' }
